version: "3.7"

services:
  client:
    build: .
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - .:/myapp/client
      - yarn-cache:/usr/local/share/.cache/yarn/v4
    env_file: .env
    command: 'yarn dev'
volumes:
  db-data:
  ? yarn-cache
